name: first_flutter_test_space
description: "A new Flutter project."
# 아래 줄은 패키지가 실수로 pub.dev에 게시되는 것을 방지합니다.
# 이는 개인 패키지에 대해 권장됩니다.
publish_to: "none" # pub.dev에 게시하려면 이 줄을 제거하세요.

# 다음은 애플리케이션의 버전과 빌드 번호를 정의합니다.
# 버전 번호는 점으로 구분된 세 개의 숫자 형식이며, 예: 1.2.43
# 선택적으로 빌드 번호가 + 뒤에 추가될 수 있습니다.
# 버전과 빌드 번호는 flutter build에서 --build-name과 --build-number를 지정하여 덮어쓸 수 있습니다.
# Android에서는 build-name이 versionName으로 사용되고, build-number는 versionCode로 사용됩니다.
# Android 버전 관리에 대한 자세한 내용은 https://developer.android.com/studio/publish/versioning에서 확인하세요.
# iOS에서는 build-name이 CFBundleShortVersionString으로 사용되고, build-number는 CFBundleVersion으로 사용됩니다.
# iOS 버전 관리에 대한 자세한 내용은
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html에서 확인하세요.
# Windows에서는 build-name이 제품 및 파일 버전의 주요, 부, 패치 번호로 사용되며,
# build-number는 빌드 접미사로 사용됩니다.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# 의존성(dependencies)은 패키지가 작동하는 데 필요한 다른 패키지를 지정합니다.
# 패키지 의존성을 최신 버전으로 자동 업그레이드하려면 `flutter pub upgrade --major-versions` 명령어를 실행하세요.
# 또는 의존성 버전을 수동으로 최신 버전으로 변경할 수 있습니다. 최신 버전 확인을 위해 `flutter pub outdated`를 실행하세요.
dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_rating_bar:

  # 아래 줄은 애플리케이션에 Cupertino Icons 글꼴을 추가합니다.
  # iOS 스타일 아이콘을 사용하려면 CupertinoIcons 클래스를 사용하세요.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # "flutter_lints" 패키지는 좋은 코딩 관행을 권장하는 lint 세트를 포함하고 있습니다.
  # 이 lint 세트는 패키지의 루트에 있는 `analysis_options.yaml` 파일에서 활성화됩니다.
  # 이 파일에서 특정 lint 규칙을 비활성화하거나 추가 규칙을 활성화할 수 있습니다.
  flutter_lints: ^4.0.0

# 이 파일에서 Dart 관련 부분에 대한 자세한 내용은
# 다음 페이지에서 확인할 수 있습니다: https://dart.dev/tools/pub/pubspec

# 다음 섹션은 Flutter 패키지에 특정한 내용입니다.
flutter:
  assets:
    - assets/

  # 아래 줄은 Material Icons 글꼴이 애플리케이션에 포함되도록 하여
  # material Icons 클래스를 사용하여 아이콘을 사용할 수 있도록 합니다.
  uses-material-design: true

  # 애플리케이션에 자산을 추가하려면, 아래와 같이 assets 섹션을 추가하세요:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 이미지 자산은 해상도에 맞는 "변형"을 지정할 수 있습니다. 자세한 내용은
  # https://flutter.dev/to/resolution-aware-images에서 확인하세요.

  # 패키지 의존성에서 자산을 추가하는 방법에 대한 자세한 내용은
  # https://flutter.dev/to/asset-from-package에서 확인하세요.

  # 애플리케이션에 사용자 정의 글꼴을 추가하려면, "flutter" 섹션 내에 fonts 섹션을 추가하세요.
  # 이 목록의 각 항목에는 "family" 키에 글꼴 이름을, "fonts" 키에는
  # 자산과 글꼴에 대한 다른 설명을 포함하는 목록이 있어야 합니다. 예:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 패키지 의존성에서 글꼴을 추가하는 방법에 대한 자세한 내용은
  # https://flutter.dev/to/font-from-package에서 확인하세요.
